config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  devise_for :users
  root to: "pages#home"
  resources :pubs do
    resources :favourites, only: :create
    resources :reviews
    resources :locals
    resources :rooms
    resources :room_messages
  end
  get "pubs/:id", to: "pubs#random"
  get "dogs/new", to: "dogs#new"
  get "dogs/:id/edit", to: "dogs#edit"
  post "dogs", to: "dogs#create"
  delete "dogs/:id", to: "dogs#destroy"
  resources :reviews
  resources :dogs
  post "room_messages", to: "room_messages#create"

  resources :users do
    resources :favourites, only: :index
  end
  resources :favourites, only: :destroy
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { minimum: 1 }
  validates :breed, presence: true, length: { minimum: 1 }
  validates :proffession, presence: true, length: { minimum: 1 }
  validates :age, presence: true
  has_one_attached :photo
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dogs = Dog.where(user: current_user)
    @dog = Dog.new
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new(params[:id])
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    if @dog.save
      redirect_to dogs_path
    else
      redirect_to dogs_path
    end
  end
  # def create
  #   @dog = Dog.create(dog_params)
  #   if @dog.save!
  #     flash[:success] = 'Dog created successfully!'
  #     redirect_to dogs_path(@dog)
  #   else
  #     flash[:error] = 'ERROR: Activity was not saved!'
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    redirect_to dogs_path(@dog)
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to dogs_path, status: :see_other
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :breed, :proffession, :age, :user_id, :photo)
  end

end

app/views/dogs/edit.html.erb
<div class= "form-containerr">
  <div class= "form-inputs">

    <h2><strong>Update your pupper</strong> </h2>
      <%= simple_form_for([@dog]) do |f| %>
        <div class="form-bar">
          <%= f.input :name %>
        </div>
        <div class="form-bar">
          <%= f.input :breed %>
        </div>
        <div class="form-bar">
          <%= f.input :age %>
        </div>
        <div class="form-bar">
          <%= f.input :proffession %>
        </div>
        <div class="form-bar">
          <%= f.input :photo, as: :file,
                    required: true %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Update", class: "btn-primary" %>
        </div>
      <% end %>
  </div>

  <%# <%= link_to "Remove", dog_path(dog), class: "btn-primary-delete m-2 ", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
</div>

app/views/dogs/index.html.erb
<div class="flex-box-dogs">
  <div class="page-title">
  <h1> My Dogs</h1>
  </div>
  <button type="button" class="btn btn-primary-chat m-3" data-bs-toggle="modal" data-bs-target="#addDog">
    Add furry friend
  </button>
</div>

<!-- Button trigger modal -->
<div class="row justify-content-center">
    <% @dogs.each do |dog| %>
      <div class="card-dog">
        <% if dog.photo.attached? %>
          <%= cl_image_tag dog.photo.key, height: 50, width: 50, class: "img-dog" %>
        <% else %>
          <p> Attach a photo of a dog </p>
        <% end %>
        <br>
        <br>
        <h5> <strong> <%= dog.name %> </strong></h5>
        <h6><strong>Breed:</strong> <%= dog.breed %></h6>
        <h6><strong>Profession:</strong> <%= dog.proffession %></h6>
        <h6><strong>Age:</strong> <%= dog.age %></h6>
        <div class="local-review-buttons justify-content-space-around">
          <%= link_to "Edit info", edit_dog_path(dog), class: "btn btn-primary m-2"%>
        </div>
      </div>
    <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="addDog" tabindex="-1" aria-labelledby="addDogLabel" aria-hidden="true" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header-color">
        <h1 class="modal-title fs-5" id="addDogLabel">Add a new dog</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <div class="modal-body">
            <%= simple_form_for([@dog]) do |f| %>
              <div class="form-bar">
                <%= f.input :name %>
              </div>
              <div class="form-bar">
                <%= f.input :breed %>
              </div>
              <div class="form-bar">
                <%= f.input :age %>
              </div>
              <div class="form-bar">
                <%= f.input :proffession, label: 'Profession' %>
              </div>
              <div class="form-bar">
                <%= f.input :photo, as: :file,
                          required: true %>
              </div>
              <div class="modal-footer"> </div>
              <div class="form-actions">
                <%= f.button :submit, "Add friend", class: "btn-primary-chat"%>
              </div>
            <% end %>
        </div>
    </div>
  </div>
</div>

app/views/dogs/new.html.erb
<div>
  <strong>new dog</strong>
<hr>
</div>
<div class= "containerr">
  <div class = "card">
    <%= form_with model: @dog do |f| %>
        <%= f.label :Name %>
        <%= f.text_field :name %>
        <%= f.label :Breed %>
        <%= f.text_field :breed %>
        <%= f.label :profession %>
        <%= f.text_field :proffession %>
        <%= f.label :Age %>
        <%= f.number_field :age %>
        <hr>
      <div class="button-div">
        <%= f.submit  class: "btn-new"%>
      </div>
    <% end %>
  </div>
  <div class= "card">
  TODO img cloudinary
  </div>
</div>

app/views/dogs/show.html.erb
 <div class= "containerr">
  <div class="dog-card">
    <h5><%= @dog.name %></h5>

    <h6><strong>Name:</strong> <%= @dog.name %></h6>

    <h6><strong>Breed:</strong> <%= @dog.breed %></h6>

    <h6><strong>Profession:</strong> <%= @dog.proffession %></h6>

    <h6><strong>Age:</strong> <%= @dog.age %></h6>
  </div>
</div>