config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  devise_for :users
  root to: "pages#home"
  resources :pubs do
    resources :favourites, only: :create
    resources :reviews
    resources :locals
    resources :rooms
    resources :room_messages
  end
  get "pubs/:id", to: "pubs#random"
  get "dogs/new", to: "dogs#new"
  get "dogs/:id/edit", to: "dogs#edit"
  post "dogs", to: "dogs#create"
  delete "dogs/:id", to: "dogs#destroy"
  resources :reviews
  resources :dogs
  post "room_messages", to: "room_messages#create"

  resources :users do
    resources :favourites, only: :index
  end
  resources :favourites, only: :destroy
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="info">
    <p>BoozeHounds Inc.  Privacy  Terms  Company Details</p>
  </div>
  <div class="icons">
    <h3 class="fa-brands fa-facebook"></h3>
    <h3 class="fa-brands fa-instagram"></h3>
    <h3 class="fa-brands fa-twitter"></h3>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <h1> Booze|Hounds </h1>
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand item" do %>
      <%= image_tag "https://img.freepik.com/premium-vector/cool-dog-is-holding-root-beer-illustration_194428-2130.jpg?w=2000", class: "w-auto" %>
        <script src="https://cdn.lordicon.com/ritcuqlt.js"></script>
    <% end %>
    <div class="d-flex justify-content-between nav-width">
      <%= link_to "Home", "/", class: "navbtn"%>
      <%= link_to "Pubs", pubs_path, class: "navbtn"%>
      <%= link_to "Chat", rooms_path, class: "navbtn"%>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="btn-dice" data_toggle="tooltip" data_placement="bottom" title="Feeling lucky? Find a random pub">
        <% if Pub.all.first %>
          <% min = Pub.all.first.id %>
          <% max = Pub.all.last.id %>
          <% random = rand(min..max) %>
          <%= link_to "", pub_path(random), class: "nav-link fa-solid fa-dice"  %>
        <% end %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar-large", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "dog-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "My Dogs", dogs_path, class: "dropdown-item" %>
            <%= link_to "My Favourites", user_favourites_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>