config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  devise_for :users
  root to: "pages#home"
  resources :pubs do
    resources :favourites, only: :create
    resources :reviews
    resources :locals
    resources :rooms
    resources :room_messages
  end
  get "pubs/:id", to: "pubs#random"
  get "dogs/new", to: "dogs#new"
  get "dogs/:id/edit", to: "dogs#edit"
  post "dogs", to: "dogs#create"
  delete "dogs/:id", to: "dogs#destroy"
  resources :reviews
  resources :dogs
  post "room_messages", to: "room_messages#create"

  resources :users do
    resources :favourites, only: :index
  end
  resources :favourites, only: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room
  belongs_to :pub
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!


  def index
    @rooms = Room.all
    @room_messages = RoomMessage.all
  end

  def show
    @pub = Pub.find(params[:pub_id])
    @room = Room.find(params[:id])
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)

  end

  def new
    @room = Room.new
    @pub = Pub.find(params[:pub_id].to_i)
  end

  def create
    @room = Room.new permitted_parameters
    # @room.pub = params[:pub_id]
    @pub = Pub.find(params[:pub_id].to_i)
    @room.pub = @pub
    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to pub_path(@pub)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(permitted_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  private

  def load_entities
    @room = Room.find(pub_id: params[:pub_id])
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/views/rooms/_form.html.erb
<%= simple_form_for [pub, room] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/rooms/_rooms.html.erb
<%#
<% if @rooms.present? %>
  <%# <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%# <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <%# <% end %>
  <%# </nav> %>
<%# <% else %>
  <%# <div class="text-muted">
    The are no rooms
  </div>
<% end %>

<%# <div class="mt-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    <%# Create a room
  <% end %>
<%# </div> %>

app/views/rooms/edit.html.erb
<h1>
  Editing room <%= @room.name %>
</h1>

<%= render partial: 'form' %>

app/views/rooms/index.html.erb
<div class="containerr mt-3">
  <h2>Have a chin wag with hounds in your area: </h2>
  <br>

  <div class="row">
    <div class="col-12 col-md-3">
      <%= render partial: 'rooms' %>
    </div>

    <div class="col">
      <div class="alert alert-primary">
        <h4 class="alert-heading">
          Welcome to BoozeHound Chat!
        </h4>

        <p>
          Talk with your fellow locals!
        </p>

        <hr />

        <p>
          You can join a room from the sidebar.
        </p>
      </div>
    </div>
  </div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, pub_room_path(room.pub, room), class: 'nav-link room-nav-link'%>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>


</div>

app/views/rooms/new.html.erb
<div class="form-container">
  <div class="form-inputs">
    <h1>
    Create a room for your favourite pub!
    </h1>

    <%= render partial: 'form', locals: {pub: @pub, room: @room} %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container2">

	<div class="bird-container bird-container--one">
		<div class="bird bird--one"></div>
	</div>

	<div class="bird-container bird-container--two">
		<div class="bird bird--two"></div>
	</div>

	<div class="bird-container bird-container--three">
		<div class="bird bird--three"></div>
	</div>

	<div class="bird-container bird-container--four">
		<div class="bird bird--four"></div>
	</div>

</div>


<div class="containerr-chat">
  <div class="chat-header"> </div>
    <h1>
       <%= @room.name %> Chat
    </h1>
  <br>
  </div>

    <div class="col" data-controller="room-subscription" data-room-subscription-room-id-value="<%= @room.id %>">
      <div class="container room">
        <div class="room_messages chat" data-room-subscription-target="messages">
          <% @room_messages.each do |room_message| %>
            <%# <%= room_message.user.username %> 
            <%= render "room_messages/room_message", room_message: room_message %>
          <% end %>
        </div>
      </div>

      <div class = "container room">
        <%= simple_form_for @room_message, html: { data: { action: "turbo:submit-end->room-subscription#resetForm" } } do |form| %>
          <div class="input-group mt-4">
            <%= form.input :message, as: :string,
                                    wrapper: false,
                                    label: false,
                                    input_html: {
                                      class: 'chat-input'
                                    } %>
            <div class="input-group-append">
              <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
            </div>
          </div>
          <%= form.input :room_id, as: :hidden %>
        <% end %>
    <%= link_to "<- Back", pub_path(@pub), class: "btn btn-primary-delete ml-3"  %>
   </div>
  </div>
</div>


</div>