config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  devise_for :users
  root to: "pages#home"
  resources :pubs do
    resources :favourites, only: :create
    resources :reviews
    resources :locals
    resources :rooms
    resources :room_messages
  end
  get "pubs/:id", to: "pubs#random"
  get "dogs/new", to: "dogs#new"
  get "dogs/:id/edit", to: "dogs#edit"
  post "dogs", to: "dogs#create"
  delete "dogs/:id", to: "dogs#destroy"
  resources :reviews
  resources :dogs
  post "room_messages", to: "room_messages#create"

  resources :users do
    resources :favourites, only: :index
  end
  resources :favourites, only: :destroy
end

app/models/pub.rb
class Pub < ApplicationRecord
  geocoded_by :postcode
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :reviews
  has_many :locals
  has_one_attached :photo
  has_many :favourites
  has_one :room
end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController

  def index

    # @pub = Pub.new
    # @pubs = Pub.all
    if params[:search].present?
      Query.create(title: params[:search])
      @search = Geocoder.search(params[:search]).first
      @pubs = Pub.near([@search.coordinates[0], @search.coordinates[1]], 0.5)
      # if list_condition
      #   @pubs = Pub.near([@search.coordinates[0], @search.coordinates[1]], 0.5)
      #   selected_filters = params.keys.select { |key| params[key] == "1" }
      #   selected_filters.each { |f| @pubs = @pubs.where(f => true) && Pub.near([@search.coordinates[0], @search.coordinates[1]], 0.5) }
      # end
    elsif params[:query].present?
      @pubs = Pub.where("name ILIKE ?", "%#{params[:query]}%")
      # elsif list_condition
      # selected_filters = params.keys.select { |key| params[key] == "1" }
      # selected_filters.each { |f| @pubs = @pubs.where(f == true && "name ILIKE ?", "%#{params[:query]}%") }

    elsif list_condition
      # THIS IS TO MAKE THE FILTERS APPLY ONLY AROUND THE GIVEN POSTCODE
      @query = Query.last.title
      @search = Geocoder.search(@query).first
      @pubs = Pub.near([@search.coordinates[0], @search.coordinates[1]], 0.5)

      # @pubs = Pub.all
      selected_filters = params.keys.select { |key| params[key] == "1" }
      selected_filters.each { |f| @pubs = @pubs.where(f => true) }
      # @pubs = Pub.where("name ILIKE ?", "%#{query_string}%")
    else
      @pubs = Pub.all
    end

    # if params[:garden].present?
    #   @pubs = @pubs.where(garden: true)
    # end

    # if list_condition
    #   if params[:search].present?
    #     search = Geocoder.search(params[:search]).first
    #     @pubs = Pub.near([search.coordinates[0], search.coordinates[1]], 0.5)
    #     selected_filters = params.keys.select { |key| params[key] == "1" }
    #     selected_filters.each { |f| @pubs = @pubs.where(f => true && Pub.near([search.coordinates[0], search.coordinates[1]], 0.5)) }
    #   end
    #   raise
    # end


    @markers = @pubs.geocoded.map do |pub|
      {
        lat: pub.latitude,
        lng: pub.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {pub: pub})
      }
    end


    # @markers = @pubs.geocoded.map do |pub|
    #   {
    #     lat: pub.latitude,
    #     lng: pub.longitude,
    #     info_window_html: render_to_string(partial: "info_window", locals: {pub: pub})
    #   }
    # end
  end


  # def myindex (if needed for my favourite pubs)
  #   @pubs = Pub.where(user_id: current_user.id)
  # end

  def show
    @pub = Pub.find(params[:id])
    @review = Review.new
    @local = Local.new
    @dog = Dog.new
    @favourite = Favourite.new
    @room = Room.new
  end

  def new
    @pub = Pub.new(params[:id])
  end

  def random
    @minimum = Pub.all.first.id
    @max = Pub.all.last.id
    @random = rand(@minimum..@max)
  end

  def create
    @pub = Pub.new(pub_params)
    @pub.user = current_user
    if @pub.save
      redirect_to pub_path(@pub)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pub = Pub.find(params[:id])
  end

  def update
    @pub = Pub.find(params[:id])
    @pub.update(pub_params)
    redirect_to pubs_path(@pub)
  end

  def destroy
    @pub = Pub.find(params[:id])
    @pub.destroy
    redirect_to pubs_path, status: :see_other
  end

  private

  def list_condition
    params.keys.include?("garden") || params.keys.include?("parking") || params.keys.include?("live_sport") || params.keys.include?("wheelchair_accessible") || params.keys.include?("food_menu")
  end

  def pub_params
    params.require(:pub).permit(:name, :address, :description, :opening_time, :closing_time, :website, :phone_number,
                                :pool_table, :non_alcoholic_drinks_selection, :garden, :parking, :live_sport,
                                :wheelchair_accessible, :food_menu)
  end
end

app/views/pubs/_info_window.html.erb
<div class="popup-marker"><%= pub.name %></div>

app/views/pubs/index.html.erb
<div class="containerr">
  <div class="container">
      <div class="searchbar">
        <%= form_with url: pubs_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search pubs..."
          %>
          <%= submit_tag "GO!", class: "btn btn-dark" %>
        <% end %>
      </div>
  </div>
  <br>
  <%= form_with method: "GET", id: "filter-checkbox", class: "filtering" do |f| %>
    <%= f.submit class: "submit-button", value: "Filter:" %>
    <div>
      <%= f.check_box :garden, class: "checkbox", id: "garden" %>
      <%= f.label :garden %>
    </div>
    <div>
      <%= f.check_box :parking, class: "checkbox", id: "parking" %>
      <%= f.label :parking %>
    </div>
    <div>
      <%= f.check_box :live_sport, class: "checkbox", id: "live_sport" %>
      <%= f.label :live_sport %>
    </div>
    <div>
      <%= f.check_box :non_alcoholic_drinks_selection, class: "checkbox", id: "non_alcoholic_drinks_selection" %>
      <%= f.label :non_alcoholic_drinks_selection, "NA Drinks" %>
    </div>
    <div>
      <%= f.check_box :wheelchair_accessible, class: "checkbox", id: "wheelchair_accessible" %>
      <%= f.label :wheelchair_accessible, "Accessible" %>
    </div>
    <div>
      <%= f.check_box :food_menu, class: "checkbox", id: "food_menu" %>
      <%= f.label :food_menu %>
    </div>
  <% end %>

  <br>
  For postcode: <%= Query.last.title.upcase %>. We have found <em><%= @pubs.length %></em> results for your search of:
  <% filter_results = params.keys.select { |key| params[key] == "1" } %>
  <% filter_results %>
  <em><%= filter_results.map {|word| word.split("_").map(&:capitalize).join(" ") }.join(", ") %></em>
  <div class="index-columns">
    <div class="row justify-content-center">
      <% @pubs.each do |pub| %>
        <%= link_to pub_path(pub), class:"card col-5" do %>
            <%= cl_image_tag pub.photo.key, class:"pub-image-card" %>
            <p class="pub-info-card" id="pub-name" ><strong><%= pub.name %></strong></p>
            <p class="pub-info-card" id="pub-times" >Opening/Closing times:
            <small>
            <% if pub.opening_time < Time.now.hour %>
              <% if pub.closing_time - Time.now.hour == 1 %>
                <%= "Closing soon" %>
              <% else %>
                <%= "Open" %>
              <% end %>
            <% else %>
              <% if pub.opening_time - Time.now.hour == 1 %>
                <%= "Opening soon" %>
              <% else %>
                <%= "Closed" %>
              <% end %>
            <% end %>
            </small>
            </p>
        <% end %>

      <% end %>
    </div>
    <div class="top_index mr-3">
      <div id="map" style="width: 500px; height: 720px"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/pubs/show.html.erb
<div class="containerr">
  <br>
  <div class="view-page-top">
    <h1><%= @pub.name %></h1>
      <% unless @pub.room.nil? %>
        <%= link_to "Enter chatroom!", pub_room_path(@pub, @pub.room), class: "btn-primary-chat" %>
      <% else %>
        <%= link_to "Enter chatroom!", new_pub_room_path(@pub), class: "btn-primary-chat" %>
      <% end %>
  </div>

<%# Pub image and information %>
    <div class="show-flex-box">
            <%= cl_image_tag @pub.photo.key, class:"pub-image-card-show" %>
      <div class="show-card-text">
        <img class="" src="#" alt="">
        <div class="card-body">
            <h4 class="card-title"><strong> <%= @pub.name %> </strong></h4>
            <br>
            <h5 class="card-text"><strong> Address:  </strong>  <%= @pub.address %></p></h5>
            <h5 class="card-text"><strong> Description:  </strong>  <%= @pub.description %></p></h5>
            <h5 class="card-text"><strong> Phone Number:  </strong>  <%= @pub.phone_number %></p></h5>

        <div class="icon-filter-card">
          <% if @pub.garden? %>
            <%= image_tag "https://res.cloudinary.com/dfi8ju7lr/image/upload/v1678876894/Booze/Pubs/Filter-icons/garden_icon_fq2yax.png" %>
          <% end %>
          <% if @pub.non_alcoholic_drinks_selection? %>
            <%= image_tag "https://res.cloudinary.com/dfi8ju7lr/image/upload/v1678876894/Booze/Pubs/Filter-icons/non_alcoholic_selection_icon_c3xvkf.png" %>
          <% end %>
          <% if @pub.live_sport? %>
            <%= image_tag "https://res.cloudinary.com/dfi8ju7lr/image/upload/v1678876894/Booze/Pubs/Filter-icons/live_sport_icon_f230vm.png" %>
          <% end %>
          <% if @pub.wheelchair_accessible? %>
            <%= image_tag "https://res.cloudinary.com/dfi8ju7lr/image/upload/v1678876894/Booze/Pubs/Filter-icons/wheelchair_accessible_icon_cvbims.png" %>
          <% end %>
          <% if @pub.food_menu? %>
            <%= image_tag "https://res.cloudinary.com/dfi8ju7lr/image/upload/v1678876894/Booze/Pubs/Filter-icons/food_menu_icon_enpf49.png" %>
          <% end %>
          <% if @pub.parking? %>
            <%= image_tag "https://res.cloudinary.com/dfi8ju7lr/image/upload/v1678876894/Booze/Pubs/Filter-icons/parking_icon_pvcftz.png"  %>
          <% end %>
        </div>
        <div class="local-review-buttons">

          <% if user_signed_in? %>
            <% if current_user.dogs.present? %>
              <%# this button adds a local %>
              <button type="button" class="btn-primary-delete" data-bs-toggle="modal" data-bs-target="#localModal">
                Add a Local
              </button>
                <div class="modal fade" id="localModal" tabindex="-1" aria-labelledby="localModal" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header-color">
                        <h1 class="modal-title fs-5" id="localModal">Add a Local</h1>
                      </div>
                        <div class="modal-body">
                          <%= simple_form_for [@pub, Local.new] do |f| %>
                            <div class="form-bar">
                              <%= f.association :dog, collection: current_user.dogs %>
                            </div>
                            <div class="form-bar">
                              <%= f.input :photo, as: :file %>
                            </div>
                             <div class="modal-footer">
                                <div class="form-actions">
                              <%= f.submit "Add your local", class: "btn btn-primary-chat" %>
                              </div>
                            </div>
                          <% end %>
                        </div>
                    </div>
                  </div>
              </div>
            <% else %>
                <button type="btn" class="add-dog-button" data-bs-toggle="modal" data-bs-target="#addDog">
                  Add a dog!
                </button>
                <div class="modal fade" id="addDog" tabindex="-1" aria-labelledby="addDog" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header-color">
                        <h1 class="modal-title fs-5" id="addDog">Add a new dog</h1>
                      </div>
                      <div class="modal-body">
                        <%= simple_form_for([@dog]) do |f| %>
                          <div class="form-bar">
                          </div>
                            <%= f.input :name %>
                          <div class="form-bar">
                            <%= f.input :breed %>
                          </div>
                          <div class="form-bar">
                            <%= f.input :age %>
                          </div>
                          <div class="form-bar">
                            <%= f.input :proffession %>
                          </div>
                          <div class="form-bar">
                            <%= f.input :photo, as: :file,
                                      required: true %>
                          </div>
                          <div class="form-actions">
                            <%= f.button :submit, "Add your dog" %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
            <% end %>
          <% else %>
            <p> Login to add a Local.</p>
          <% end %>
          <% if user_signed_in? %>
            <button type="button" class="btn-primary" data-bs-toggle="modal" data-bs-target="#reviewModal"> Leave a review </button>
              <div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header-color">
                      <h1 class="modal-title fs-5" id="reviewModalLabel">Leave a review</h1>
                    </div>
                      <div class="modal-body">
                        <%= simple_form_for([@pub, @review]) do |f| %>
                          <div class="form-bar">
                            <%= f.input :content %>
                          </div>
                            <%= f.label :rating %>
                          <div class="form-bar rating">
                            <input name="review[rating]" id="e5" type="radio" value="5"><label for="e5">★</label>
                            <input name="review[rating]" id="e4" type="radio" value="4"><label for="e4">★</label>
                            <input name="review[rating]" id="e3" type="radio" value="3"><label for="e3">★</label>
                            <input name="review[rating]" id="e2" type="radio" value="2"><label for="e2">★</label>
                            <input name="review[rating]" id="e1" type="radio" value="1"><label for="e1">★</label>
                          </div>
                          <div class="modal-footer"></div>
                            <div class="form-actions">
                              <%= f.submit  class: "btn btn-primary-chat", label: "Leave review" %>
                            </div>
                        <% end %>
                      </div>
                  </div>
                </div>
              </div>
            <% else %>
              <p> Login to leave a review. </p>
            <% end %>
          <% if user_signed_in? %>
            <% unless current_user.favourites.where(pub_id: @pub.id).empty?%>
              <h2 class="added mr-3"><%= "⭐"%></h2>
            <% else %>
              <h2> <%=  link_to "★", pub_favourites_path(@pub), data: {turbo_method: :post}, class: "favourite-star mr-3"%> </h2>
            <% end %>
          <% else %>
            <p> Login to favourite. </p>
          <% end %>
          </div>
        </div>
      </div>
    </div>


  <%# reviews section %>
  <br>
    <div class="flex-box-local-reviews">
        <div class="flex-box-review">
          <h2>Reviews</h2>
            <% if @pub.reviews.present? %>
              <% @pub.reviews.each do |review| %>
              <div class="card-local">
                <div class="card-local-infos">
                  <h5> <strong> <%= review.user.username  %> </strong> says: </h5>
                  <h6> <%= review.content %> </h6>
                  <br>
                  <h6><% review.rating.to_i.times do %></h6>
                      <span>⭐</span>
                      <% end %>
                  </p>
                </div>
              </div>
              <% end %>
            <% else %>
              <p> Be the first to add a review </p>
            <% end %>
        </div>
  <%# Locals code, do not interfere! %>
    <div class="flex-box-local">
      <h2>Locals</h2>
        <% if @pub.locals.present? %>
          <% @pub.locals.each do |local| %>
            <div class="card-local">
              <div class="card-local-img"> <%= cl_image_tag local.photo.key, height: 50, width: 50 %> </div>
              <div class="card-local-infos">
                <h5>  <%= local.dog.name %> </h5>
                <h6> <strong> Breed: </strong>  <%= local.dog.breed %> </h6>
                <h6> <strong> Age: </strong> <%= local.dog.age %> </h6>
                <h6> <strong> Profession: </strong> <%= local.dog.proffession %> </h6>
              </div>
            </div>
          <% end %>
        <% else %>
          <p> Be the first to add a local</p>
        <% end %>
    </div>
  </div>
      <%= link_to "<-- Back", pubs_path, class: "btn btn-primary-delete"  %>
      </div>
    </div>
    </div>
  </div>
</div>